// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      print('Using web platform');
      return web ?? _throwNullOptionsError();
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        print('Using Android platform');
        return android ?? _throwNullOptionsError();
      case TargetPlatform.iOS:
        print('Using iOS platform');
        return ios ?? _throwNullOptionsError();
      case TargetPlatform.macOS:
        print('Using macOS platform');
        return macos ?? _throwNullOptionsError();
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _throwNullOptionsError() {
    throw AssertionError('FirebaseOptions cannot be null when creating the default app.');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnBtP4G-rG85IP05pB75SnHSkbrEPM5Lk',
    appId: '1:145112535030:web:128d0f28d9d4fbd83f01d7',
    messagingSenderId: '145112535030',
    projectId: 'weatherblocddd2024',
    authDomain: 'weatherblocddd2024.firebaseapp.com',
    storageBucket: 'weatherblocddd2024.appspot.com',
    measurementId: 'G-7XRD834LJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaAHDsNpfRjjG2wEZKJATnJJN0AItsc8A',
    appId: '1:145112535030:android:397578b9b02637933f01d7',
    messagingSenderId: '145112535030',
    projectId: 'weatherblocddd2024',
    storageBucket: 'weatherblocddd2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGOi9eAYeAONdNPclRSp5h1CGsLf1Ej9o',
    appId: '1:145112535030:ios:77124a369b4378203f01d7',
    messagingSenderId: '145112535030',
    projectId: 'weatherblocddd2024',
    storageBucket: 'weatherblocddd2024.appspot.com',
    iosBundleId: 'com.example.weatherBlocDdd2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGOi9eAYeAONdNPclRSp5h1CGsLf1Ej9o',
    appId: '1:145112535030:ios:36090b4a20ff543f3f01d7',
    messagingSenderId: '145112535030',
    projectId: 'weatherblocddd2024',
    storageBucket: 'weatherblocddd2024.appspot.com',
    iosBundleId: 'com.example.weatherBlocDdd2024.RunnerTests',
  );
}
